name: spotify_clone_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #svg
  flutter_svg: ^2.0.10+1
  #state managment
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  equatable: ^2.0.5
  #firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_crashlytics: ^4.1.3
  uuid:
  #dependency injection
  get_it: ^8.0.0
  #dart z
  dartz: ^0.10.1
  #audio_player
  just_audio: ^0.9.40
  #asset gen
  flutter_gen: ^5.7.0
  #auto route
  auto_route: ^9.2.2
  #flavor
  flavor: ^2.0.0
  #freezed
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  #google sign in
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  #snackbar
  modern_snackbar: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  #code generation
  build_runner:
  freezed: ^2.5.7
  auto_route_generator: ^9.0.0
  flutter_gen_runner:
  #linting
  flutter_lints: ^4.0.0
  json_serializable:
  

flutter:
  uses-material-design: true
  assets:
   - assets/images/png/
   - assets/images/svg/
   - assets/icons/svg/